version: '3.8'

services:
  postgres_app:
    image: postgres:13
    container_name: postgres_system
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pyhackdb_system_db
    ports:
      - "5432:5432"
    volumes:
      - pgsystem:/var/lib/postgresql/data
  
  postgres_vuln:
    image: postgres:13
    container_name: postgres_vuln
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    ports:
      - "5433:5432"
    volumes:
      - pgvuln:/var/lib/postgresql/data
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vuln_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/opt/mysql

  web:
    build: .
    container_name: flask_web
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - postgres_app
    environment:
      # DB da aplicação
      DB_HOST: postgres_app
      DB_PORT: 5432
      DB_NAME: pyhackdb_system_db
      DB_USER: postgres
      DB_PASS: postgres

      # DB vulnerável
      VULN_DB_HOST: postgres_vuln
      VULN_DB_PORT: 5433
      VULN_DB_NAME: todo_db
      VULN_DB_USER: postgres
      VULN_DB_PASS: postgres

volumes:
  pgsystem:
  pgvuln:
  mssql_data:
  mysql_data:
